### PR TITLE
Add i386 and X86_64 to the valid archs of eDO's project

### PR DESCRIPTION
**Pull request by tirodkar**

### CODE REVIEW

**Comment by wuhao5** [comment]
is this needed if we don't build single flat binary?

**Comment by wuhao5** [comment]
testing close and reopen

**Comment by khandpur** [comment]
This doesn't work, see failure:
https://travis-ci.org/google/eDistantObject/jobs/425561285

**Comment by khandpur** [comment]
Seems fairly obvious to me that it's related since you changed xcode project's objectVersion:

```
RuntimeError - [Xcodeproj] Unknown object version.
/Users/travis/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb:102:in `open'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:903:in `block (2 levels) in inspect_targets_to_integrate'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:902:in `each'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:902:in `block in inspect_targets_to_integrate'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:897:in `inspect_targets_to_integrate'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:69:in `analyze'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:242:in `analyze'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/pod:23:in `load'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tirodkar** [comment]
Uh oh. Yeah, the version! Shouldn't have used the latest beta version. Fixed.

**Pull request merged**
